### ISSUE TITLE
Annotate ouput

### ISSUE THREAD

**Issue by zoewardnz** [YangLab/CIRCexplorer2#11]
I have two output files when I run CIRCexplorer2 annotate:
annotated_fusion.txt   and circ_fusion.txt
Why am I getting two files? I have aligned my data with STAR but followed the rest of the parse and annotate pipeline as shown on the tutorial.

**Comment by kepbod** [comment]
You used the old version of CIRCexplorer2. From version 2.3.0, CIRCexplorer2 has very big changes in inputs and outputs. You could refer to the [old document](http://circexplorer2.readthedocs.io/en/2.2.7/) of CIRCexplorer2.
