### ISSUE TITLE
No module named dir_func

### ISSUE THREAD

**Issue by maojn** [YangLab/CIRCexplorer2#13]
$ fast_circ.py 
Traceback (most recent call last):
  File "/usr/local/apps/circexplorer/2.3.0/bin/fast_circ.py", line 4, in <module>
    import circ2.fast_circ
  File "/usr/local/Anaconda/envs_app/circexplorer/2.3.0/lib/python2.7/site-packages/CIRCexplorer2-2.3.0-py2.7.egg/circ2/fast_circ.py", line 30, in <module>
    
ImportError: No module named dir_func
======================
However, dir_func indeed exist:
$ unzip /usr/local/Anaconda/envs_app/circexplorer/2.3.0/lib/python2.7/site-packages/CIRCexplorer2-2.3.0-py2.7.egg 
$ ls -l circ2/*.py
-rw-r--r-- 1 maoj staff    0 Aug 30 01:30 circ2/__init__.py
-rw-r--r-- 1 maoj staff 9.1K Sep 15 13:43 circ2/align.py
-rw-r--r-- 1 maoj staff  11K Sep 15 13:43 circ2/annotate.py
-rw-r--r-- 1 maoj staff 7.0K Sep 15 13:43 circ2/assemble.py
-rw-r--r-- 1 maoj staff 2.3K Sep 15 13:43 circ2/command_parse.py
-rw-r--r-- 1 maoj staff  28K Sep 15 13:43 circ2/denovo.py
-rw-r--r-- 1 maoj staff  734 Aug 31 06:09 circ2/dir_func.py
-rw-r--r-- 1 maoj staff 4.0K Sep 15 13:43 circ2/fast_circ.py
-rw-r--r-- 1 maoj staff 3.3K Sep 15 13:43 circ2/fetch_ucsc.py
-rw-r--r-- 1 maoj staff 8.9K Aug 30 01:30 circ2/genomic_interval.py
-rw-r--r-- 1 maoj staff  17K Sep 15 13:43 circ2/helper.py
-rw-r--r-- 1 maoj staff 8.3K Sep 15 13:43 circ2/parse.py
-rw-r--r-- 1 maoj staff 5.5K Sep 15 13:43 circ2/parser.py
-rw-r--r-- 1 maoj staff   22 Aug 31 12:50 circ2/version.py

Thank you for your help.

Jean

**Comment by kepbod** [comment]
This is a bug of 2.3.0. Please try the new version (2.3.1). Thanks so much.
