### ISSUE TITLE
Deal with last comma of exonStarts and exonEnds

### ISSUE THREAD

**Issue by Tong-Chen** [YangLab/CIRCexplorer2#14]
Hello,

Thanks for the great tool!

One minor issue.

Would it be more safe to change line 75-76 of `circ/parser.py`

from 

```
starts = [int(x) for x in line.split()[9].split(',')[:-1]]
ends = [int(x) for x in line.split()[10].split(',')[:-1]]
```

to 

```
starts = [int(x) for x in line.split()[9].strip(',').split(',')]
ends = [int(x) for x in line.split()[10].strip(',').split(',')]
```

or other ways to deal with the last comma in case it not exists.

In my mind, it may be a historical problem for saving last comma in gene annotation file.

Best,

Tong

**Comment by kepbod** [comment]
Great idea. I will change them. Thanks so much!
