### ISSUE TITLE
gtf to txt conversion

### ISSUE THREAD

**Issue by tut3** [YangLab/CIRCexplorer2#15]
Hi, I am using circexplorer2 for my analysis and generating my own genome files for a pathogen. I have gtf, bed and fasta files for these genomes but not the txt. Is there an easy way to convert or any can I use anything else instead?

**Comment by kepbod** [comment]
For GTF file, you could try [gtfToGenePred](http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred) from UCSC to convert gtf to genepred format, and the txt file is an [extended genepred format](https://genome.ucsc.edu/FAQ/FAQformat.html#format1.7).
