### ISSUE TITLE
about alternative (back-)splicing events detection

### ISSUE THREAD

**Issue by smm19900210** [YangLab/CIRCexplorer2#2]
hi author:
The below words quoted from your website about characterization of Circular RNA Alternative Splicing
 "It requires alignment results (set using -a) of poly(A)+ RNA-seq derived from the same source of corresponding poly(A)−/ribo− RNA-seq so that it will extract circular RNA predominate alternative (back-)splicing events after comparing poly(A)−/ribo− RNA-seq with poly(A)+ RNA-seq." 

but I only have RNase+ RNA-seq data, it means that i don't detect AS event use your programes?

**Comment by kepbod** [comment]
Comparing poly(A)−/ribo− RNA-seq with poly(A)+ RNA-seq is to exclude the effect of linear RNAs in identifying circular RNA predominate alternative splicing events. From my point of view, RNase R RNA-seq samples have the same effects to some extent. So you could simply compare RNase R RNA-seq with poly(A)+ RNA-seq to identify circular RNA predominate alternative splicing events. For alternative back-splicing events, RNase R RNA-seq samples are sufficient.

**Comment by smm19900210** [comment]
thanks kepbod, but i only have RNase+ RNA-seq data, not have  poly(A)+ RNA-seq. is there another method to identify AS event of circRNA?

**Comment by smm19900210** [comment]
can i use identified circRNAs to exclude the effect of linear RNAs in identifying circular RNA predominate alternative splicing events?

**Comment by kepbod** [comment]
If your cell line/tissue is very common used in the field, you could easily obtain pA+ RNA-seq datasets from GEO.

**Comment by smm19900210** [comment]
thanks very much!
