### ISSUE TITLE
a question about align

### ISSUE THREAD

**Issue by weishuxun** [YangLab/CIRCexplorer2#20]
when the align of CIRCexplorer2 was used with a command of `tophat2 --library-type fr-unstranded -o tophat_fusion -p 46 --fusion-search --keep-fasta-order --bowtie1 --no-coverage-search bowtie1_index SRR1797218_1.fastq SRR1797218_2.fastq`，a error was run and show：
Error running bowtie:
Error while flushing and closing output
terminate called after throwing an instance of 'int'。
is there a problem with version of my software or other matter？
could you help me？
![-1](https://user-images.githubusercontent.com/40813429/42339918-123807a0-80c1-11e8-95b3-348fb679996f.jpg)

**Comment by kepbod** [comment]
This is an issue of tophat2 but not CIRCexplorer2. Maybe you could try to reinstall tophat2.
