### ISSUE TITLE
Idea about using STAR Chimeric.out.junction file for circRNA alternative splicing analysis

### ISSUE THREAD

**Issue by kepbod** [YangLab/CIRCexplorer2#21]
It seems the Chimeric.out.junction file from STAR chimeric alignment would output the internal junction information. We could use that information to analysis the internal splicing pattern of circRNAs. Our previous pipeline relied on compare the splicing pattern between samples with and without circRNA enrichment, and it has lots of limitations. Parsing Chimeric.out.junction file could directly tell the splicing pattern from the total RNA-seq dataset without other data. I have written some codes to imply this function (https://github.com/kepbod/CIRCexplorer2/blob/master/circ2/parse_as.py). I have no enough time to work on it. If you are interested in it, I hope you could push it forward. Thanks so much.

**Comment by xingma** [comment]
Thanks for your advice and related works. I will try to put it forward. @kepbod
