### ISSUE TITLE
Error when multiple instances of CIRCexplorer2 annotate run from a same directory 

### ISSUE THREAD

**Issue by egaffo** [YangLab/CIRCexplorer2#26]
Error when multiple instances of CIRCexplorer2 annotate runs from the same directory:

in annotate_fusion from annotate.py, line 51
annotated_fusion_f = 'annotated_fusion.txt.tmp'

the tmp file is overwritten by any instance of CIRCexplorer launched from the a same directory, but writing in different output files specified with -b option in "annotate".
This messes up the output of each instance.

You could prefix the tmp file with the dirname of the output file, or add an option to let the user select the tmp dir.

Enrico

**Comment by kepbod** [comment]
Thanks you for finding this bug. I have tried to fix it. Please try the latest version to see whether it works for you.
