### ISSUE TITLE
Analysis of Mitochondria

### ISSUE THREAD

**Issue by andremrsantos** [YangLab/CIRCexplorer2#27]
I wonder if at any stage during annotation you filter out mitochondrial back splice junctions? When I parse the alignment, there are some back splices listed in the back_splice_junction.bed, but when I annotate, there is none.
I tried to read the code but I couldn't find any arbitrary filter. Can you help me?

**Comment by kepbod** [comment]
We did not filter out mitochondrial back splice junctions. The annotate step requires gene annotation file to help correct most of the false positives. Some novel circRNAs without gene annotation would be filtered out in this step. Please make sure there are gene annotations in ChrM. If the gene annotations in ChrM are very few, you could use back_splice_junction.bed directly.

**Comment by andremrsantos** [comment]
Thank you @kepbod 
I do have a couple of genes in the chrM, but I think because their organization is different they are not annotated.
