### ISSUE TITLE
Issue with mm10_ens

### ISSUE THREAD

**Issue by yzh37545** [YangLab/CIRCexplorer2#32]
I am trying to use fetch_ucsc.py to get mm10. But I got the error as follows:
![image](https://user-images.githubusercontent.com/39535598/57399549-194d2f80-7197-11e9-95ee-01a1d2bd4e5a.png)

**Comment by yzh37545** [comment]
Based on my search, there is no mm10 ens annotation for known genes. Is the mm10_ens necessary in the further steps? If not, could I just use the mm10_ref?
Thank you!

**Comment by kepbod** [comment]
mm10_ens annotation is truly missing in the UCSC database. You could choose any gene annotation according to the requirement of your project. `fetch_ucsc.py` only facilitates fetching some annotation files from UCSC. There is no requirement for CIRCexplorer2 which gene annotation you choose.
