### ISSUE TITLE
Is it possible to do circexplorer2 denovo using other aligners??

### ISSUE THREAD

**Issue by sambhav2mishra** [YangLab/CIRCexplorer2#38]
Kindly suggest me any alternative to perform denovo.
when i run it manually using tophat2 or circalign, it shows me the following error:

[2019-09-17 16:53:51] Beginning TopHat run (v2.1.0)
-----------------------------------------------
[2019-09-17 16:53:51] Checking for Bowtie
                  Bowtie version:        1.2.3.0
[2019-09-17 16:53:51] Checking for Bowtie index files (genome)..
[2019-09-17 16:53:51] Checking for reference FASTA file
        Warning: Could not find FASTA file /userdata/Dramaresh/fastq_dir/GMA_alignment/bowtie1_index/bowtie1_index.fa
[2019-09-17 16:53:51] Reconstituting reference FASTA file from Bowtie index
  Executing: /userdata/Dramaresh/tools/bowtie-1.2.3-linux-x86_64/bowtie-inspect /userdata/Dramaresh/fastq_dir/GMA_alignment/bowtie1_index/bowtie1_index > /userdata/Dramaresh/fastq_dir/GMA_alignment/tophat_fusion/tmp/bowtie1_index.fa
[2019-09-17 16:55:26] Generating SAM header for /userdata/Dramaresh/fastq_dir/GMA_alignment/bowtie1_index/bowtie1_index
[2019-09-17 16:55:30] Preparing reads
         left reads: min. length=19, max. length=151, 12158285 kept reads (20688 discarded)
Warning: short reads (<20bp) will make TopHat quite slow and take large amount of memory because they are likely to be mapped in too many places
[2019-09-17 16:58:36] Mapping left_kept_reads to genome bowtie1_index with Bowtie
        [FAILED]
Error running bowtie:
Error while flushing and closing output
terminate called after throwing an instance of 'int'

Your suggestions/solution will be appreciated by our lab.
Thanks 
sambhav

**Comment by iichelhadi** [comment]
I got the same error. Have you found a solution. I tried STAR but at a certain step downstream cufflinks is necessary and my understanding is that it requires tophat.

**Comment by sambhav2mishra** [comment]
> I got the same error. Have you found a solution. I tried STAR but at a certain step downstream cufflinks is necessary and my understanding is that it requires tophat.

Try using bowtie v1.0.0 (works with specific version)

**Comment by iichelhadi** [comment]
> > I got the same error. Have you found a solution. I tried STAR but at a certain step downstream cufflinks is necessary and my understanding is that it requires tophat.
> 
> Try using bowtie v1.0.0 (works with specific version)

I used STAR because bowtie1 doesn't work for me with the same error as above. Couldn't find a solution for that either
