### ISSUE TITLE
Invalid literal for int() with base 10: 'MIR6859-1

### ISSUE THREAD

**Issue by CuypersBart** [YangLab/CIRCexplorer2#40]
![image](https://user-images.githubusercontent.com/9530810/74387756-bc536980-4df9-11ea-8c0f-d18d6ec84c79.png)

I am running: 
'CIRCexplorer2 annotate -r hg38all.txt -g hg38.fa -b back_spliced_junction.bed -o circularRNA_known.txt > CIRCexplorer2_annotate.log' with the annotation values described in the manual. However, I get the error Invalid literal for int() with base 10: 'MIR6859-1, like it is trying to convert the gene name (first column, correct according to the format) to an integer. Do you have an idea what could be going wrong here?

**Comment by kepbod** [comment]
This error occurred at [line 78 of parser.py](https://github.com/YangLab/CIRCexplorer2/blob/e0a64e6a5eacaf8654ee919d788937675a519246/circ2/parser.py#L78). It tried to parse exon start positions (column 10 of your hg38all.txt) into integers, but it encountered 'MIR6859-1' which could not be converted into integer. Could you check your file again to make sure it is in the correct format?

**Comment by kepbod** [comment]
[Here](https://raw.githubusercontent.com/YangLab/CIRCexplorer2/master/test/data/ref.txt) is the example of gene annotation file.
