### ISSUE TITLE
Does CIRCexplorer2 pipeline only works with mouse and human?? 

### ISSUE THREAD

**Issue by sambhav2mishra** [YangLab/CIRCexplorer2#45]
Dear YangLab

You guys have done an amazing piece of work. Thanks for that.
I have a question I tried to do circRNAs detection using this pipeline but in the annotation module we require a ref file (e.g hg38_ref_all.txt) but how do I perform analysis with different genome other than mouse and human?? or is this pipeline only limited to hg19/hg38/mm9/mm10?  :)

**Comment by kepbod** [comment]
If you have the genome sequence and gene annotations of the corresponding genome, you could apply CIRCexplorer on whatever genome you want. The format of gene annotations should be compatible to CIRCexplorer (https://circexplorer2.readthedocs.io/en/latest/modules/annotate/). If you have no idea how to convert file format, you could refer to Issue #43.

**Comment by sambhav2mishra** [comment]
Thank you so much. It worked perfectly.
