### ISSUE TITLE
Fail to annotate MapSplice junctions

### ISSUE THREAD

**Issue by BarryDigby** [YangLab/CIRCexplorer2#46]
Hello @kepbod, sorry to trouble you once again. 

My issue should be evident from the title so I will provide you with as much information as possible, and hopefully you might be able to shed some light as to why circexplorer produces 0 annotations for MapSplice output.  

The reference files used for this analysis are the latest GRCh38 gencode files, which you helped produce in issue #43. 

**MapSplice call**:
 ```
 gzip -d --force ${mapsplice_reads[0]}
 gzip -d --force ${mapsplice_reads[1]}

 mapsplice.py -c $genome_dir -x $bowtie_dir -1 ${base}_R1.fastq -2 ${base}_R2.fastq \
  -p 8 --bam --seglen 20 --min-map-len 40 --fusion-non-canonical --min-fusion-distance 200 \
  --gene-gtf $gtf -o $base 
```

**CIRCexplorer2 parse call**: 
```
CIRCexplorer2 parse -t MapSplice $fusion -b ${base}.mapsplice.junction.bed
```

**CIRCexplorer2 annotate call**:
```
CIRCexplorer2 annotate -r $ref_txt -g $genome -b ${base}.mapsplice.junction.bed -o ${base}.mapsplice.circRNA.txt
```

```
Start CIRCexplorer2 annotate at 16:34:52
Start to annotate fusion junctions...
Annotated 0 fusion junctions!
Start to fix fusion junctions...
Fixed 0 fusion junctions!
End CIRCexplorer2 annotate at 16:34:59
```

`$fusion` file -> [fusions_raw.txt](https://github.com/YangLab/CIRCexplorer2/files/5023013/fusions_raw.txt)

`${base}.mapslice.junction.bed` file (converted to `.txt` to upload) -> [mapslice.junction.txt](https://github.com/YangLab/CIRCexplorer2/files/5023012/3fbd2e82-95c1-40c1-86dd-bd7d2e87ab08_gdc_realn_rehead.mapsplice.junction.txt)

The junctions do overlap annotations in the `hg38.txt` file, so I am not sure why none are being called. I can provide the reference files if needed but they were produced verbatim from #43. 

Kind Regards, 

Barry

**Comment by kepbod** [comment]
Hi Barry,

I checked your command lines and found no errors. The genomic span in the junction file (mapslice.junction.txt) are too long and these junctions seem like artifacts but not circRNAs. One potential reason is about the aligner. You could try other aligner (such as STAR) to see whether you could get circRNAs. Another potential reason is there is no circRNA in your RNA-seq samples. Total RNA-seq or RNase R enrichment could help to enrich circRNAs.

Xiao-Ou

**Comment by BarryDigby** [comment]
Thank you for the prompt response

**Comment by BirongZhang** [comment]
Hi all,

Sorry to comment below the closed issue, but I ran into the same problem. I used STAR aligner, everything is fine before annotation.

Here is my STAR command and junction output(Homo_sapiens.GRCh38.103.gtf):
```
STAR \
--runMode alignReads \
--genomeDir $genome \
--runThreadN $cores \
--readFilesIn $fq \
--sjdbGTFfile $gtf  \
--outFileNamePrefix $align_out \
--outSAMtype BAM SortedByCoordinate \
--chimSegmentMin 10 \
--chimOutType Junctions \
--chimOutJunctionFormat 0
```
<img width="1026" alt="Screenshot 2021-10-13 at 18 28 31" src="https://user-images.githubusercontent.com/74430395/137183396-5aa71dfa-e00a-403c-8766-adba587004b9.png">

Here is my parse command and output:
```
 CIRCexplorer2 parse -t STAR Chimeric/SRR13199991_Chimeric.out.junction > CIRCexplorer2_parse.log
```
<img width="611" alt="Screenshot 2021-10-13 at 18 30 06" src="https://user-images.githubusercontent.com/74430395/137183616-1cc05b8f-ac6c-4b6b-b479-32ea140ebbc5.png">

Here is my annotation command and output:
```
CIRCexplorer2 annotate -r hg19_ref_all.txt -g hg19.fa -b back_spliced_junction.bed -o circularRNA_known.txt > CIRCexplorer2_annotate.log
```
<img width="598" alt="Screenshot 2021-10-13 at 18 32 00" src="https://user-images.githubusercontent.com/74430395/137183847-dd9e2c05-0bf8-4cdc-be89-e40998758e58.png">

Then I got a zero byte circularRNA_known.txt file. So could you help me to have  a look at my command? If my command is correct, then as you said before, this data won't find any circular RNA. 
Thanks.

Kind regards,
Birong
