### ISSUE TITLE
CIRCexplorer2  annotate doesn't support multiple rows command 

### ISSUE THREAD

**Issue by gnilihzeux** [YangLab/CIRCexplorer2#5]
Actually I find CIRCexplorer2 annotate seems not support linux continue operater `\` just as below:

```
CIRCexplorer2 annotate -r ~/hg38_ens.txt \
-g ~/ensembl_grch38.fa \
~/circ_out \
> CIRCexplorer2_annotate.log
```
Even just one \.
I wish this could be solved because of the ugly format of full path. Maybe mine is an exception.

**Comment by kepbod** [comment]
CIRCexplorer2 uses [docopt](https://github.com/docopt/docopt) to parse commands, and shell command in one line is the most convenient way. I think this requested feature is not necessary.
