### ISSUE TITLE
Annoted 0 fusion junction

### ISSUE THREAD

**Issue by JerryZhang-1222** [YangLab/CIRCexplorer2#55]
hello sir！First thanks a lot for providing a fantanstic tool for circRNA identification!
I have an issue about the annotate step: **all of the output files are empty**.
I checked my bed files and they all seem to be right, and the genepred file for Rattus which I made by myself is also in the correct position. 
Also I noticed that some of the donor sites and the accepter sites in the bed files are almost corresponed to the exon start sites and end sites in the genepred files but missed a few hundreds of bps and that made my very confused.

**here is the log file:**
> CIRCexplorer parameters: /home/zhangfy/miniconda3/envs/RNAseq/bin/CIRCexplorer2 annotate -r /home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/Rattus.genepred -g /home/zhangfy/data_projects/RNAseq/LW_MPP/reference/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa -b /home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/3_parse/6_back_spliced_junction.bed -o 6_circularRNA_known.txt
> Start CIRCexplorer2 annotate at 00:13:48
> Start to annotate fusion junctions...
> Annotated 0 fusion junctions!
> Start to fix fusion junctions...
> Fixed 0 fusion junctions!
> End CIRCexplorer2 annotate at 00:13:51

**here are the first few lines of one of the bed files:**
> MT      15477   15689   FUSIONJUNC_0/2  0       +
> 19      32562077        47681809        FUSIONJUNC_1/1  0       +
> 1       44056455        44077618        FUSIONJUNC_2/1  0       +
> 6       76200504        76205352        FUSIONJUNC_3/2  0       +
> 5       91136795        91136896        FUSIONJUNC_4/1  0       +
> 5       91128426        91128652        FUSIONJUNC_5/2  0       +
> 16      8883292 8883871 FUSIONJUNC_6/1  0       +
> 13      67311522        67312186        FUSIONJUNC_7/1  0       +
> 13      95128659        95348984        FUSIONJUNC_8/3  0       +
> 11      38351756        38352109        FUSIONJUNC_9/1  0       +
> X       65291486        65295744        FUSIONJUNC_10/2 0       +
> 8       68647568        68647772        FUSIONJUNC_11/1 0       +
> 13      7179473 7179726 FUSIONJUNC_12/2 0       +
> 3       174787719       175367022       FUSIONJUNC_13/1 0       +
> 9       113516802       113518802       FUSIONJUNC_14/3 0       +

and here is my code:
```
#!/bin/bash
cat files.txt | while read id;
do echo $id
        arr=($id) 
        sample=${arr[0]}
        ref_dir=/home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/Rattus.genepred
        fa_dir=/home/zhangfy/data_projects/RNAseq/LW_MPP/reference/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa
        bed_dir=/home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/3_parse/${sample}_back_spliced_junction.bed
        nohup CIRCexplorer2 annotate \
                -r ${ref_dir} \
                -g ${fa_dir} \
                -b ${bed_dir} \
                -o ${sample}_circularRNA_known.txt> annotate.log 2>&1 &
done
```

I've attahced all of the files mentioned above:
1. **back_spliced junction.txt**  is one of the output bed files after the parsing step.
2. **annotate.log** is the log file. 
3. **annotate.txt**  is my bash script while the **files.txt** is a namelist that will be needed in the bash script.
4. **Rattus.txt** is the reference genepred file. 
[1_back_spliced_junction.txt](https://github.com/YangLab/CIRCexplorer2/files/6845637/1_back_spliced_junction.txt)
[annotate.log](https://github.com/YangLab/CIRCexplorer2/files/6845638/annotate.log)
[annotate.txt](https://github.com/YangLab/CIRCexplorer2/files/6845639/annotate.txt)
[files.txt](https://github.com/YangLab/CIRCexplorer2/files/6845640/files.txt)
[Rattus.txt](https://github.com/YangLab/CIRCexplorer2/files/6845641/Rattus.txt)

Thanks again!
 Zhangfy

**Comment by kepbod** [comment]
The chrom column in your back_spliced junction file did not have 'chr', but your Rattus.txt had. Please make sure they are consistent.

**Comment by JerryZhang-1222** [comment]
> 
> 
> The chrom column in your back_spliced junction file did not have 'chr', but your Rattus.txt had. Please make sure they are consistent.

Thank you! That perfectly soved my problem!
