### ISSUE TITLE
skip comment lines of STAR chimeric output file

### ISSUE THREAD

**Issue by gudeqing** [YangLab/CIRCexplorer2#56]
Hi,  to avoid potential exceptions, I think we should skip the lines starting with '#' in Chimeric.out.junction,  such as the following lines:
```
# 2.7.8a   STAR --runThreadN 6 --genomeDir /cromwell-executions/rnaseq_pipeline/......(**This line will be printed when set "--chimOutJunctionFormat 1"**)
# Nreads 931	NreadsUnique 18	NreadsMulti 0
```
best wishes!

**Comment by kepbod** [comment]
Please set `--chimOutJunctionFormat` to 0 (the default value) to not output comments in Chimeric.out.junction. See [STAR manual](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf) for details.
