### ISSUE TITLE
CIRCpedia download

### ISSUE THREAD

**Issue by mumichae** [YangLab/CIRCexplorer2#57]
Hi,

I have a question on the [CIRCpedia download](https://www.picb.ac.cn/rnomics/circpedia/download). The download file doesn't contain any headers, is there any place I can find them?

Best,
M

**Comment by kepbod** [comment]
Please refer to the Figure 2 of [the CIRCpedia v2 paper](https://www.sciencedirect.com/science/article/pii/S1672022918302596).
