### ISSUE TITLE
Annotated 0 fusion junctions

### ISSUE THREAD

**Issue by snehamurthy21** [YangLab/CIRCexplorer2#6]
CIRCexplorer parameters: /usr/local/bin/CIRCexplorer2 annotate -r ref.txt -g ref.fa circ
Start CIRCexplorer2 annotate at 11:44:56
Start to annotate fusion junctions...
Annotated 0 fusion junctions!
Start to fix fusion junctions...
Fixed 0 fusion junctions!
End CIRCexplorer2 annotate at 11:45:01

why would i get 0 fusion junctions could anyone suggest what to try?

**Comment by kepbod** [comment]
The expression of circRNAs is extremely low, so correct sequencing method and sufficient sequencing depth should be satisfied. Please make sure your datasets are correct.
