### ISSUE TITLE
What is hg19_ref_all.txt file?

### ISSUE THREAD

**Issue by mathavanpu** [YangLab/CIRCexplorer2#62]
Hi
The annotate step need this file hg19_ref_all.txt, I want to know is that  file representing the human GTF file? 
or 
how I can generate the file (hg19_ref_all.txt)

**Comment by davhum** [comment]
Hi Mathavanpu, 

If am not sure where you identify a file called "hg19_ref_all.txt", can you let me know? The annotation steps are documented in vignette (or via https://github.com/VCCRI/Sierra/wiki/Sierra-Vignette)  and do utilise a gtf file .

**Comment by erdaqorri** [comment]
@mathavanpu Hi, were you able to figure out how to generate this file "hg19_ref_all.txt"?

**Comment by kepbod** [comment]
Please refer to the [CIRCexplorer2 manual](https://circexplorer2.readthedocs.io/en/latest/tutorial/setup/).
