### ISSUE TITLE
CIRCexplorer2 support for STAR paired-end reads

### ISSUE THREAD

**Issue by iprada** [YangLab/CIRCexplorer2#9]
Hi! As Tophat/Tophat-fusion has gone into a low maitenance period, it would be great to have an implementation that supports STAR aligned, paired-end reads. 

Do you plan to have that in the future?

**Comment by kepbod** [comment]
Currently there is no big difference between parsing STAR aligned paired-end reads and single reads for CIRCexplorer2. The only issue is that CIRCexplorer2 could not use the information of mate reads to filter out false positives like Tophat. I will try to figure out how to further improving STAR parser in CIRCexplorer2 to support using those information.

**Comment by kepbod** [comment]
I have tested different cases how STAR outputs Chimeric.out.junction, and I found STAR reports chimeric junctions only when the mate read also supports this chimeric alignment. In other words, current version of CIRCexplorer2 could also be applied to STAR aligned, paired-end reads. I will update the documents later.

**Comment by iprada** [comment]
That sounds great! I woud run my samples trough it!
